name: smude
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - pytorch-lightning
  - scikit-image
  - scipy
  - torchvision
  - tqdm
  - requests
  - pip
  - pip:
    - opencv_contrib_python
